import streamlit as st
import pandas as pd
import pickle
import numpy as np
import os 
model=pickle.load(open('model.pkl','rb'))
def predict_factor(list2):
	list1=list2
	print(list2)
	age1=list1[0]
	zone1=list1[2]
	weight=list1[10]
	del list1[0]
	del list1[2]
	del list1[8]
	if age1=='A':
		list1.append(1)
	else:
		list1.append(0)
	if age1 == 'C':
		list1.append(1)
	else:
		list1.append(0)
	if age1=='T':
		list1.append(1)
	else:
		list1.append(0)
	if age1=='O':
		list1.append(1)
	else:
		list1.append(0)
	if age1=='I':
		list1.append(1)
	else:
		list1.append(0)
	if zone1=='S':
		list1.append(1)
	else:
		list1.append(0)
	if zone1 == 'B':
		list1.append(1)
	else:
		list1.append(0)
	if zone1=='A':
		list1.append(1)
	else:
		list1.append(0)
	if zone1=='R':
		list1.append(1)
	else:
		list1.append(0)
	if weight=='N':
		list1.append(1)
	else:
		list1.append(0)
	if weight == 'O':
		list1.append(1)
	else:
		list1.append(0)
	if weight=='S':
		list1.append(1)
	else:
		list1.append(0)
	print(list1)
	input1=np.array([list1]).astype(np.float64)
	prediction=model.predict(input1)
	return prediction
def main():
	st.set_page_config(layout="wide")
	html_temp = """
	<div style="background-color:DarkBlue;"><p style="color:white;font-size:60px;font:Optima"> <center> C O V i D I S E R</center></p></div>
	"""
	st.markdown(html_temp,unsafe_allow_html=True)

	html_temp1 = """
	<div style="background-color:Grey;"><p style="color:white;font-size:40px;font:TimesNewRoman"> <center> Your COVID Advisor</center></p></div>
	"""
	st.markdown(html_temp1,unsafe_allow_html=True)






	st.subheader("This web-app will let you check your susceptibility to the covid-19 virus \
	as well it is also going to tell you whether you must immediately need a vaccine or not. Decision taken is based on your age, location of stay, job and other various health conditions. Datasets and public health info. all that are taken into account, are mostly respective to india and subject to constant change. ")
	st.text("")
	st.text("")
	st.text("")
	st.text("")
	st.text("")
	st.text("")
	st.text("")
	st.text("")
	st.text("")
	st.text("")
	st.text("")
	st.text("")


	html_header = """
	<div ;"><p style="color:Black;font-size:30px;font:CourierNew">READ MORE ABOUT THE WEB-APP AND IT'S TASK</p></div>
	"""
	st.markdown(html_header,unsafe_allow_html=True,)

	with st.beta_expander("Expand"):
		st.subheader("Details of the people who will be using this app shall be taken in, to analyse the current health condition of the person. and then the expected risk of his/her virus infection is evaluated. This will help in distributing the limited supply of vaccines in the hands of the needy. Thus, prioritisation of vaccines explained in layman's terms.")
		st.text("")
		st.text("")
		st.text("")
		st.text("")


		st.subheader(" 24 inputs shall be taken  from the user end, and a risk factor will be generated by the underlying model. Besides a Percentile shall also be shown which depicts when may your turn come up in the vaccination queue for covid-19 ")
		st.text("")
		st.text("")
		st.text("")
		st.text("")
		st.text("")

		if st.checkbox("INPUTS?"):
			st.info(" Inputs corresponds to data collected from user to use it for the actual task. Factors may be biological or health related which is quite obvious; and also it could be physical like type of job, stay address, age, covid test results if done. \n 24 inputs comprises :")
			c1,c2=st.beta_columns(2)
			c1.info("20 biological factors")
			c2.info("4 other non-biological factors")
		if st.checkbox("RISK FACTORS?"):
			st.info("The result that's going to be generated after user finishes the test is essentially the Risk Factor. Value ranges from 1 to 99 in 100. As it naturally signifies, as the value closes 99, or as the risk factor for a particular case grows, it tells that the vaccination of this case should be given higer priority as opposed to perhaps another case who risk factor is supposedly lower than the former case mentioned. A message or a breif classification, based on the risk factor shall also be shown.")
		if st.checkbox("PERCENTILE?"):
			st.info("Imagine you're standing in a covid-19 vaccination queue, to get vaccinated. But no. of vaccines are limited. So it's not your usual case of getting into a queue to grab a sim card or anything else, which are mostly based on first-come-first-serve business. Rather to explain it further, in the normal case of queues it's usually only the limitation of time. But here the limitation that poses the greater challenge is quantity(supply/production), besides the time-bounded limitation being already present. \n So,  long story in short is, the percentile figure will roughly get you an idea about your position in the queue. It's calculated based on the risk factor generated in your case. Based on cases stored in our databases, we check the number of persons having risk factor figure higher or lower than yours, the total no. of cases stored in the database and things alike")
			st.text("If A: Total no.of cases having risk factor less than yours, \n   B: Total no. of cases recorded at this point of time")
			st.text("Formula for Percentile is (A/B)*100")
			st.info("Hence, this shows the percentage of people who expectedly might get vaccinated after you. Obviously so, (100-percentile)% of people will quite possibly get their vaccine before you will get yours. But remember data stored in our database cannot ever represent all groups and sets of population in India. So discrepancies may be observed. Though calculations and predictions can expectedly become more and more accurate with extensive usage, and extensive types of data.")



	st.text("")
	st.text("")

	st.header("WHAT'S PRIORITISATION? \n WHAT ARE WE WORKING ON?")
	with st.beta_expander("See"):
		st.success('''"Prioritising who gets the vaccine" \n It's great that we now have COVID-19 vaccines that have been approved for general use. However, that's not the end of the COVID story just yet. Millions of doses of vaccines now have to be produced and injected into the arms of people. That is one massive manufacturing, logistical, and time-consuming task for everyone involved. It is all going to take time. The first phase of the vaccination programme focuses on saving lives and reducing hospital admissions. So it is logical to give the vaccine first to those groups that are most vulnerable - older people and those with pre-existing conditions.''')
		st.write("read more about vaccines over here [W.H.O. website](https://www.who.int/news-room/q-a-detail/vaccines-and-immunization-what-is-vaccination?adgroupsurvey={adgroupsurvey})")
		st.write("read about prioritisation of vaccines in these recommended articles:  \t  [BBC News](https://www.bbc.com/news/world-asia-india-55048925),     \t  [TheHindu](https://www.thehindu.com/sci-tech/science/prioritising-who-gets-vaccinated-against-covid-19-can-save-lives-study/article34244795.ece),   \t  [Business Standard](https://www.business-standard.com/article/current-affairs/retailers-body-appeals-to-prioritise-covid-19-vaccine-for-workers-121031700467_1.html),    \t  [ncbi.nlm.nih.gov](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7743091/),  \t    [Bloomberg](https://www.bloomberg.com/news/articles/2020-10-29/india-to-prioritize-covid-vaccine-for-front-line-health-workers)")

	st.header("Below is the graph \n that visually depicts or pictorises the risk factor distribution among the population set that has been considered for building this web application. If you're going to use this application, your result will also be used for conclusion. We'll urge you to go ahead.")
	# if st.checkbox("Show", value=True):
	# 	cov19data=pd.read_csv('covidx_final.csv')
	# 	st.text(" Distribution of 'Risk factor ranging from 0.01-0.99' V/S 'Frequency'")
	# 	graph_display=pd.DataFrame(cov19data['Risk Factor'].value_counts()).head(800)
	# 	st.bar_chart(graph_display)




	st.text("")
	st.text("")
	st.text("")
	st.text("")

	html_temp1 = """
	<div style="background-color:tomato"><p style="color:white;font-size:30px;font:Sans-serif">&nbsp;TAKE THE TEST</p></div>
	"""
	st.markdown(html_temp1,unsafe_allow_html=True)
	x=["Yes","No"]
	with  st.beta_expander("Start"):
		if st.checkbox("I have already got myself vaccinated."):
			st.write("Then you don't need this test. Hence, we're not proceeding with the same.")
			st.write("Thank You, for your time")
			st.info("Uncheck to get back to the test.")
		else:
			s1=st.selectbox("1) Age--",["0-3 years old","4-14 years old","15-24 years old","25-55 years old","above 56 years old"])

			if s1=="0-3 years old":
				s1='I'
			if s1=="4-14 years old":
				s1='C'
			if s1=="15-24 years old":
				s1='T'
			if s1=="25-55 years old":
				s1='A'
			if s1=="above 56 years old":
				s1='O'

			s2=st.selectbox("2) Are you a Front Line worker?",x)
			if s2=="Yes":
				s2=1
			if s2=="No":
				s2=0




			s3=st.selectbox(" 3) What were your covid antibody test results?",["Positive","Negative","Not done yet"])
			if s3=="Positive":
				s3=1
			if s3=="Negative":
				s3=0
			if s3=="Not done yet":
				s3=0






			s4=st.selectbox("4) In which zone does your home address falls in, by the following classification? ",["Safe Zone","Red Zone","Buffer Zone","Affected Zone"])
			if s4=="Safe Zone":
				s4='S'
			if s4=="Red Zone":
				s4='R'
			if s4=="Buffer Zone":
				s4='B'
			if s4=="Affected Zone":
				s4='A'








			s5=st.selectbox("5) Do you have Cancer?",x)
			if s5=="Yes":
				s5=1
			if s5=="No":
				s5=0




			s6=st.selectbox("6) Have you ever been diagnosed with Chronic kidney disease?",x)
			if s6=="Yes":
				s6=1
			if s6=="No":
				s6=0



			s7=st.selectbox("7) Do you have Chronic Obstructive pulmonary disease (C.O.P.D.)?",x)
			if s7=="Yes":
				s7=1
			if s7=="No":
				s7=0




			s8=st.selectbox("8) Were you diagnosed with Down Syndrome?",x)
			if s8=="Yes":
				s8=1
			if s8=="No":
				s8=0




			s9=st.selectbox("9) Do you have any kind of heart conditions in your body, like angina coronary artery diseases or cardiomyopathies?",x)
			if s9=="Yes":
				s9=1
			if s9=="No":
				s9=0




			s10=st.selectbox("10) Are you in an immunocompromised state (weakened immune system) resulting from solid organ transplant or(/and) HIV?",x)
			if s10=="Yes":
				s10=1
			if s10=="No":
				s10=0


			s11=st.selectbox("11) What is your Nutritional status?   *BMI units in kg/sq.m.", ["Normal (18<BMI<=25)","Overweight (25<BMI<=30)","Obesity (30<BMI<=36)","Underweight (BMI<=18)","Severe Obesity (BMI>36) "])
			st.write("You can also check your BMI (Body Mass Index) from here and then input accordingly >> [BMI Calculator](https://www.nhlbi.nih.gov/health/educational/lose_wt/BMI/bmicalc.htm)")

			if s11=="Normal (18<BMI<=25)":
				s11='N'
			if s11=="Overweight (25<BMI<=30)" or s11=="Obesity (30<BMI<=36)":
				s11='O'
			if s11=="Underweight (BMI<=18)" or s11=="Severe Obesity (BMI>36) ":
				s11='S'





			s12=st.selectbox("12) Are you in state of Pregnancy?",x)
			if s12=="Yes":
				s12=1
			if s12=="No":
				s12=0



			s13=st.selectbox("13) Do you have Sickle cell disease?",x)
			if s13=="Yes":
				s13=1
			if s13=="No":
				s13=0



			s14=st.selectbox("14) You smoke?",x)
			if s14=="Yes":
				s14=1
			if s14=="No":
				s14=0




			s15=st.selectbox("15) Were you ever diagnosed with Type 2 Diabetes Mellitus?",x)
			if s15=="Yes":
				s15=1
			if s15=="No":
				s15=0




			s16=st.selectbox("16) Having moderate-to-severe Asthma?",x)
			if s16=="Yes":
				s16=1
			if s16=="No":
				s16=0



			s17=st.selectbox("17) Do you have Cerebro-vascular diseases?",x)
			if s17=="Yes":
				s17=1
			if s17=="No":
				s17=0



			s18=st.selectbox("18) Do you have Hypertension or high Blood Pressure?",x)
			if s18=="Yes":
				s18=1
			if s18=="No":
				s18=0




			s19=st.selectbox("19) Are you facing any Neurological conditions, such as, Dementia?",x)
			if s19=="Yes":
				s19=1
			if s19=="No":
				s19=0



			s20=st.selectbox("20) Are you having Liver Diseases?",x)
			if s20=="Yes":
				s20=1
			if s20=="No":
				s20=0



			s21=st.selectbox("21) Do you have Pulmonary Fibrosis (i.e. having damaged or scarred lung tissues)",x)
			if s21=="Yes":
				s21=1
			if s21=="No":
				s21=0



			s22=st.selectbox("22) Do you have Thalassemia (a kind of blood disorder) / Aplastic Anemia",x)
			if s22=="Yes":
				s22=1
			if s22=="No":
				s22=0



			s23=st.selectbox("23) Do you have Decompensated Cirrhosis?",x)
			if s23=="Yes":
				s23=1
			if s23=="No":
				s23=0



			s24=st.selectbox("24) Do you have Type 1 Diabetes Mellitus?",x)
			if s24=="Yes":
				s24=1
			if s24=="No":
				s24=0

			selection=[s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21,s22,s23,s24]
			if st.button("Predict"):
				output=predict_factor(selection)
				st.success("the risk factor is")
				st.write(output)
if __name__=='__main__':
	main()









		





	
     






if st.sidebar.beta_expander("About Us and the Project"):
	pass
st.text("")
st.text("")
st.text("")
st.text("")
st.text("")



